Traceback (most recent call last):
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/envs/engr131/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#create optimized y-data for best fit curve
opt_y = func(x_data,*popt) #popt[0]*np.sin(popt[1]*x_data)

#lets plot it
fig, ax = plt.subplots(figsize=(6,6))
ax.scatter(x_data,y_data, color = 'green', label ='OG Data') #Plot original data

ax.plot(x_data,opt_y, color = 'black', label = 'Best Fit Curve') #Plot best fit curve on same plot

#Make it pretty 
ax.legend()
ax.set_title('Sine Plot', size = 15) #changing the font size to 15 here with the size parameter 
ax.set_xlabel('x-data', size = 15)
ax.set_ylabel('y-data', size = 15)
ax.tick_params(axis='x', labelsize=12) #one of many ways you can change the tick label sizes
ax.tick_params(axis='y', labelsize=12)

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 2[0m
[1;32m      1[0m [38;5;66;03m#create optimized y-data for best fit curve[39;00m
[0;32m----> 2[0m opt_y [38;5;241m=[39m [43mfunc[49m(x_data,[38;5;241m*[39mpopt) [38;5;66;03m#popt[0]*np.sin(popt[1]*x_data)[39;00m
[1;32m      4[0m [38;5;66;03m#lets plot it[39;00m
[1;32m      5[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots(figsize[38;5;241m=[39m([38;5;241m6[39m,[38;5;241m6[39m))

[0;31mNameError[0m: name 'func' is not defined

